// get list of recipes
GET http://192.168.178.31:3000/my-recipes

###

// get list of recipes with custom query
GET http://192.168.178.31:3000/my-recipes?sortBy=cookTimeTotal

###

// get falafel recipe data
GET http://192.168.178.31:3000/recipe/falafel

###

// post new recipe
POST http://192.168.178.31:3000/edit
Content-Type: application/json

{
    "recipeName": "Fried Pötatoes",
    "cookTimeTotal": 45,
    "cookTimeActive": 45,
    "tags": ["Vegan"],
    "quantity": 2,
    "quantityUnit": "Portions",
    "ingredients": "Ingredients here.",
    "body": "Instructions here."
}

###

// filler recipe
POST http://192.168.178.31:3000/edit
Content-Type: application/json

{
    "recipeName": "filler",
    "cookTimeTotal": 1,
    "cookTimeActive": 1,
    "tags": [],
    "quantity": 1,
    "quantityUnit": "",
    "ingredients": "",
    "body": ""
}

###

// delete specified recipe
DELETE http://192.168.178.31:3000/edit/falafel-2

###

// save recipe
POST http://192.168.178.31:3000/save/falafel
Content-Type: application/json

{
    "saved": true
}

###

// unsave recipe
POST http://192.168.178.31:3000/save/falafel
Content-Type: application/json

{
    "saved": false
}