GET http://localhost:3000/
//redirect to /my-recipes

###

GET http://localhost:3000/my-recipes
//show list of recipes TBD

###

GET http://localhost:3000/my-recipes?sortBy=cookTimeTotal&sortDir=1

###

GET http://localhost:3000/recipe/
//redirect to /my-recipes

### 

GET http://localhost:3000/recipe/falafel
//show falafel recipe page TBD

###

GET http://localhost:3000/edit
//show empty edit page TBD

###

POST http://localhost:3000/edit
Content-Type: application/json

{
    "recipeName": "Fried Pötatoes",
    "cookTimeTotal": 45,
    "cookTimeActive": 45,
    "tags": ["Vegan"],
    "quantity": 2,
    "quantityUnit": "Portions",
    "body": "Ingredients and instructions here."
}

###

DELETE http://localhost:3000/edit/falafel-2

###

GET http://localhost:3000/edit/falafel
//show edit page with loaded falafel recipe data TBD