GET http://localhost:3000/
//redirect to /my-recipes

###

GET http://localhost:3000/my-recipes
//show list of recipes TBD

###

GET http://localhost:3000/my-recipes?sortBy=cookTimeTotal&sortDir=1

###

GET http://localhost:3000/recipe/
//redirect to /my-recipes

### 

GET http://localhost:3000/recipe/falafel
//show falafel recipe page TBD

###

GET http://localhost:3000/edit
//show empty edit page TBD

###

POST http://localhost:3000/edit
Content-Type: application/json

{
    "urlName": "fried-potatoes",
    "recipeName": "Fried Potatoes",
    "cookTimeTotal": "45",
    "cookTimeActive": "45",
    "dateAdded": 1000000000000,
    "tags": ["Vegan"],
    //"quantity": 2, TODO
    //"quantity_unit": "portions",
    "ingredients": ["Potatoes", "Spices of Choice", "Salt", "Oil"],
    "instructions": "slice potatoes, mix with spices, and fry until ready"
}

###

DELETE http://localhost:3000/edit/fried-potatoes

###

GET http://localhost:3000/edit/falafel
//show edit page with loaded falafel recipe data TBD